# Calculating and Creating New Metrics

Calculations and creating new meterics in python is very simple and it can open up a whole world of benchmarks and metrics in which to govern your marketing activities. In this notebook we'll look various ways of creating and caltulating metrics.

In [2]:
import pandas as pd # importing pandas library

In [3]:
ga_gsc_data = pd.read_csv('C:/Users/ysman/Documents/springboard/Timeseries Python Linkedin/Ex_Files_Python_Marketing/Ex_Files_Python_Marketing/Exercise Files/data/other_data/ga_gsc_data.csv')

In [4]:
ga_gsc_data.head()

,Unnamed: 0,Page,Clicks,Impressions,CTR,Position,Avg. Time on Page,Bounce Rate,Exit,Pageviews,Unique Pageviews
0,0,https://miratrix.co.uk/,371,100673,0.37%,42.59,0 days 00:01:43.666666666,47.296667,54.286667,1396,1095
1,1,https://miratrix.co.uk/app-marketing-agency/,80,30824,0.26%,26.84,0 days 00:01:45.333333333,64.436667,60.913333,210,181
2,2,https://miratrix.co.uk/mobile-app-competitor-a...,16,1458,1.1%,30.64,0 days 00:04:06,53.335000,89.475000,30,26
3,3,https://miratrix.co.uk/blippar-the-message-isn...,11,517,2.13%,36.05,0 days 00:00:22.333333333,58.170000,78.333333,27,21
4,4,https://miratrix.co.uk/author/nduddy/,10,140,7.14%,5.61,0 days 00:02:52,22.223333,38.890000,15,13

In [5]:
ga_gsc_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         193 non-null    int64
 1   Page               193 non-null    object
 2   Clicks             193 non-null    int64
 3   Impressions        193 non-null    int64
 4   CTR                193 non-null    object
 5   Position           193 non-null    float64
 6   Avg. Time on Page  193 non-null    object
 7   Bounce Rate        193 non-null    float64
 8   Exit               193 non-null    float64
 9   Pageviews          193 non-null    int64
 10  Unique Pageviews   193 non-null    int64
dtypes: float64(3), int64(5), object(3)
memory usage: 16.7+ KB

## Caluculating metrics in Pandas

In this section you'll recalculate the the CTR field and replace the current object with a float. You will also create two new metrics from the current data you have.

In [6]:
#Calculating CTR and replace the CTR column
ga_gsc_data.CTR = (ga_gsc_data.Clicks.div(ga_gsc_data.Impressions)*100).round(2)

In [6]:
ga_gsc_data.CTR.head()

0    0.37
1    0.26
2    1.10
3    2.13
4    7.14
Name: CTR, dtype: float64

From the bouce percentage lets calculate the a interger value for number of visitors that bounced. We can use this to create another CTR meteric which will show us how many loyal visitors are clicking through.

In [7]:
#Calculate the number of bounces
ga_gsc_data['num_bounces'] = (ga_gsc_data['Clicks'] - (ga_gsc_data.Exit.div(100).multiply(
    ga_gsc_data['Clicks']))).astype(int)

In [8]:
ga_gsc_data.head()

,Unnamed: 0,Page,Clicks,Impressions,CTR,Position,Avg. Time on Page,Bounce Rate,Exit,Pageviews,Unique Pageviews,num_bounces
0,0,https://miratrix.co.uk/,371,100673,0.37,42.59,0 days 00:01:43.666666666,47.296667,54.286667,1396,1095,169
1,1,https://miratrix.co.uk/app-marketing-agency/,80,30824,0.26,26.84,0 days 00:01:45.333333333,64.436667,60.913333,210,181,31
2,2,https://miratrix.co.uk/mobile-app-competitor-a...,16,1458,1.10,30.64,0 days 00:04:06,53.335000,89.475000,30,26,1
3,3,https://miratrix.co.uk/blippar-the-message-isn...,11,517,2.13,36.05,0 days 00:00:22.333333333,58.170000,78.333333,27,21,2
4,4,https://miratrix.co.uk/author/nduddy/,10,140,7.14,5.61,0 days 00:02:52,22.223333,38.890000,15,13,6

In [9]:
ga_gsc_data.insert(4, #position
                   'CTR true visits', #name of column 
                   (ga_gsc_data.num_bounces.div(ga_gsc_data.Impressions)*100).round(2) #value
                  )

In [10]:
ga_gsc_data.head()

,Unnamed: 0,Page,Clicks,Impressions,CTR true visits,CTR,Position,Avg. Time on Page,Bounce Rate,Exit,Pageviews,Unique Pageviews,num_bounces
0,0,https://miratrix.co.uk/,371,100673,0.17,0.37,42.59,0 days 00:01:43.666666666,47.296667,54.286667,1396,1095,169
1,1,https://miratrix.co.uk/app-marketing-agency/,80,30824,0.10,0.26,26.84,0 days 00:01:45.333333333,64.436667,60.913333,210,181,31
2,2,https://miratrix.co.uk/mobile-app-competitor-a...,16,1458,0.07,1.10,30.64,0 days 00:04:06,53.335000,89.475000,30,26,1
3,3,https://miratrix.co.uk/blippar-the-message-isn...,11,517,0.39,2.13,36.05,0 days 00:00:22.333333333,58.170000,78.333333,27,21,2
4,4,https://miratrix.co.uk/author/nduddy/,10,140,4.29,7.14,5.61,0 days 00:02:52,22.223333,38.890000,15,13,6

## Filtering Data

We all need to filter data regularly, it's a daily task. Filtering data in pandas simple as long as you remember the <a href="https://www.tutorialspoint.com/python/python_basic_operators.htm">correct basic operator</a> to use e.g >= or <=.

In [11]:
#Filter the data by pages that have recieved 100 or more clicks
ga_gsc_data[ga_gsc_data['Clicks'] >= 100]

,Unnamed: 0,Page,Clicks,Impressions,CTR true visits,CTR,Position,Avg. Time on Page,Bounce Rate,Exit,Pageviews,Unique Pageviews,num_bounces
0,0,https://miratrix.co.uk/,371,100673,0.17,0.37,42.59,0 days 00:01:43.666666666,47.296667,54.286667,1396,1095,169

In [12]:
#Filter the data by pages that have recieved 100 or more clicks
filter1 = ga_gsc_data[(ga_gsc_data['Position'] <= 10) & (ga_gsc_data['Impressions'] >= 100)]

In [13]:
filter1

,Unnamed: 0,Page,Clicks,Impressions,CTR true visits,CTR,Position,Avg. Time on Page,Bounce Rate,Exit,Pageviews,Unique Pageviews,num_bounces
4,4,https://miratrix.co.uk/author/nduddy/,10,140,4.29,7.14,5.61,0 days 00:02:52,22.223333,38.89,15,13,6
14,14,https://miratrix.co.uk/miratrix-23-golden-squa...,3,227,0.00,1.32,7.59,0 days 00:00:00,0.000000,100.00,4,4,0
34,36,https://miratrix.co.uk/droidcon-not-just-for-d...,1,166,0.00,0.60,8.00,0 days 00:00:00,0.000000,100.00,1,1,0

In [14]:
#Filter and sort your data 
ga_gsc_data[ga_gsc_data['Impressions'] >= 1000].sort_values(by="CTR true visits",
                                                            ascending=False)

,Unnamed: 0,Page,Clicks,Impressions,CTR true visits,CTR,Position,Avg. Time on Page,Bounce Rate,Exit,Pageviews,Unique Pageviews,num_bounces
0,0,https://miratrix.co.uk/,371,100673,0.17,0.37,42.59,0 days 00:01:43.666666666,47.296667,54.286667,1396,1095,169
1,1,https://miratrix.co.uk/app-marketing-agency/,80,30824,0.10,0.26,26.84,0 days 00:01:45.333333333,64.436667,60.913333,210,181,31
2,2,https://miratrix.co.uk/mobile-app-competitor-a...,16,1458,0.07,1.10,30.64,0 days 00:04:06,53.335000,89.475000,30,26,1
8,8,https://miratrix.co.uk/app-store-optimization-...,5,4177,0.02,0.12,70.02,0 days 00:01:31.666666666,61.906667,60.256667,198,160,1
82,93,https://miratrix.co.uk/seo-agency-london/,0,1496,0.00,0.00,215.61,0 days 00:00:32.500000,100.000000,66.665000,4,4,0